### ISSUE TITLE
[regression] dnf5 not finding grup install target but dnf4 does

### ISSUE THREAD

**Issue by solomoncyj** [rpm-software-management/dnf5#1666] opened 2024-08-31 01:35 UTC
command: 
```
dnf group install "Budgie Desktop"
```
 ## dnf5
 ```
 Repositories loaded.
Failed to resolve the transaction:
No match for argument: Budgie Desktop
You can try to add to command line:
  --skip-unavailable to skip unavailable packages
  ```
  
  * * * 

## dnf4
```
Copr repo for dnf5-testing-nightly owned by rpmsoftwaremanagement                                                                                                  1.0 kB/s | 1.5 kB     00:01    
Copr repo for dnf5-testing-nightly owned by rpmsoftwaremanagement                                                                                                   77 kB/s | 136 kB     00:01    
Docker CE Stable - x86_64                                                                                                                                           23 kB/s | 9.7 kB     00:00    
determining the fastest mirror (3 hosts).. done.                              100% [=============================================================================]  22 kB/s |  11 kB     00:00 ETA
Fedora 40 - x86_64                                                                                                                                                 7.6 kB/s |  11 kB     00:01    
Fedora 40 openh264 (From Cisco) - x86_64                                                                                                                           1.3 kB/s | 989  B     00:00    
Fedora 40 - x86_64 - Updates                                                                                                                                       8.6 kB/s | 8.7 kB     00:01    
Fedora 40 - x86_64 - Updates                                                                                                                                       275 kB/s | 5.2 MB     00:19    
RPM Fusion for Fedora 40 - Free                                                                                                                                    8.4 kB/s |  12 kB     00:01    
RPM Fusion for Fedora 40 - Free - Updates                                                                                                                           15 kB/s |  11 kB     00:00    
RPM Fusion for Fedora 40 - Free - Updates                                                                                                                           43 kB/s |  74 kB     00:01    
RPM Fusion for Fedora 40 - Nonfree                                                                                                                                  16 kB/s |  16 kB     00:01    
RPM Fusion for Fedora 40 - Nonfree - Updates                                                                                                                        19 kB/s |  15 kB     00:00    
RPM Fusion for Fedora 40 - Nonfree - Updates                                                                                                                        15 kB/s |  26 kB     00:01    
WineHQ packages                                                                                                                                                     89 kB/s |  36 kB     00:00    
Dependencies resolved.
===================================================================================================================================================================================================
 Package                                                Architecture                Version                                                   Repository                                      Size
===================================================================================================================================================================================================
Installing group/module packages:
 NetworkManager-openconnect-gnome                       x86_64                      1.2.10-5.fc40                                             fedora                                          46 k
 NetworkManager-openvpn-gnome                           x86_64                      1:1.12.0-1.fc40                                           updates                                         70 k
 NetworkManager-pptp-gnome                              x86_64                      1:1.2.12-6.fc40                                           fedora                                          41 k
 NetworkManager-ssh-gnome                               x86_64                      1.2.13-1.fc40                                             fedora                                          34 k
 NetworkManager-vpnc-gnome                              x86_64                      1:1.2.8-7.fc40                                            fedora                                          38 k
 atril                     
 [....]
 ```

**Comment by ppisar** [comment] 2024-09-02 08:55
That's a feature. DNF5 only supports group identifiers when installing a group. DNF4 attempted to match against group display names. Problem with display names is that they depend on a locale, they are not unique and they can change anytime. Please you group identifiers. You can list them with `dnf5 group list`.

**Comment by ppisar** [comment] 2024-09-02 08:58
Duplicate of #1599.

**Closed by ppisar** 2024-09-02 08:58 UTC
