### ISSUE TITLE
dnf5 outputs status messages to stdout (dnf 4 sent them to stderr)

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/dnf5#1545] opened 2024-06-11 07:18 UTC
Compare:

    dnf --disablerepo=* --enablerepo=openqa-testtag repoquery --qf "%{SOURCERPM} %{NAME} %{EPOCH} %{VERSION} %{RELEASE}\n" > /mnt/updatepkgs.txt

    dnf-3 --disablerepo=* --enablerepo=openqa-testtag repoquery --qf "%{SOURCERPM} %{NAME} %{EPOCH} %{VERSION} %{RELEASE}\n" > /mnt/updatepkgs.txt

the dnf-3 version prints its status messages - download progress on the repo, then "Last metadata expiration check: 0:00:02 ago on Tue 11 Jun 2024 12:14:28 AM." - to the console, and they are not in `/mnt/updatepkgs.txt`. With the dnf5 version, nothing appears on the console, and the messages wind up at the top `/mnt/updatepkgs.txt`:

```
Updating and loading repositories:
Repositories loaded.
0ad-0.0.26-21.fc41.src.rpm 0ad 0 0.0.26 21.fc41
...
```

If I add `2 > &1` to the dnf-3 command, the messages end up in the file, so clearly older dnf sent its status messages to stderr. This seems like better behaviour, because now I have to do additional work to avoid status messages polluting this file I'm trying to generate.

**Comment by AdamWill** [comment] 2024-06-11 07:26
I figured that adding `-q` suppresses these messages entirely, which works for this case, but still...

**Comment by kontura** [comment] 2024-06-11 08:06
This is a duplicate of https://github.com/rpm-software-management/dnf5/issues/1361.

**Closed by kontura** 2024-06-11 08:06 UTC
