### ISSUE TITLE
pt-br translation errors

### ISSUE THREAD

**Issue by x-gyba** [rpm-software-management/dnf5#1911] opened 2024-11-28 12:00 UTC
![Captura de tela de 2024-11-28 08-52-48](https://github.com/user-attachments/assets/49dd9a9e-2425-498b-9ea1-f729ba3b8946)

similar error: Terminado!ando  and caregado instead of carregado.

**Comment by ppisar** [comment] 2024-11-28 14:59
Indeed. It's a duplicate of #1899.

**Closed by ppisar** 2024-11-28 14:59 UTC

**Comment by eduardo-antunes** [comment] 2024-11-29 23:12
Sorry for commenting on a closed issue, I don't know if this is something you do not encourage. However, after reading through #1899, I do believe that the second error cited by @x-gyba (caregado, with just one R, rather than carregado) is unrelated to it. I think it's probably just a typo, and a trivial fix.

**Comment by sunwire** [comment] 2024-11-30 08:54
> I think it's probably just a typo, and a trivial fix.

Is that what you mean?
https://translate.fedoraproject.org/translate/dnf5/dnf5/pt_BR/?checksum=5b0d454908dfe0b9&q=Loaded+Repositories&sort_by=-priority%2Cposition

Looks like someone already fixed it

**Comment by eduardo-antunes** [comment] 2024-11-30 15:27
Looks like it. Thanks for responding!
