### ISSUE TITLE
Provide useful dnf5 package in the dnf5-unstable Copr repo for Fedora 38 and older

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#567] opened 2023-05-26 13:32 UTC
For Fedora 39, we expcet the `/bin/dnf` (symlink) and `dnf` (provide) to be provided by the `dnf5` package.

This isn't ideal for Fedora 38, unless we want to be super intrusive.  On F38, `/bin/dnf` is still provided by the `dnf` package which should stay installed from the default repositories.

**Comment by jan-kolarik** [comment] 2023-05-26 14:33
Changes are pushed, following Copr nightlies will hopefully resolved this issue.

**Comment by j-mracek** [comment] 2023-05-29 14:38
In theory we should keep the issue opened until the successful build in nightly, but from upstream perspective the issue is resolved, therefore I am closing it.

**Closed by j-mracek** 2023-05-29 14:38 UTC
Labels: Priority: HIGH, Triaged
