### ISSUE TITLE
install does not satisfy missing dependencies of an installed package

### ISSUE THREAD

**Issue by t184256** [rpm-software-management/dnf5#1498] opened 2024-05-16 10:30 UTC
The `install` command does not do what it claims to do, specifically it doesn't bother satisfying missing dependencies when the package is already installed, but the dependencies are missing.

> The install command in DNF5 is used for installing packages. It makes sure that all given packages defined in package-spec arguments and their dependencies are installed on the system.

How to reproduce:
1. upgrade to rawhide
2. `dnf download glances`
3. `rpm -i --nodeps glances*.rpm`
4. `dnf install glances`

Observed behaviour:
```
Updating and loading repositories:
 Fedora rawhide - x86_64                100% | 239.6 KiB/s |   4.3 KiB |  00m00s
Repositories loaded.
Package "glances-3.4.0-5.fc40.noarch" is already installed.
```

dnf did not, in fact, make sure that "all given packages ... and their dependencies are installed on the system."

Expected behaviour:

dnf downloads and installs all missing direct and transitive dependencies of glances

**Comment by t184256** [comment] 2024-05-20 14:56
`dnf reinstall glances` reinstalls glances and satisfies the dependencies. But I don't want to reinstall (in my actual case, it's about a package that dnf rejects, but RPM can be forced to install), just satisfy the dependencies.

`dnf5 check` detects the problem, but it doesn't offer a way to satisfy the dependencies.

IMO, there are, broadly, at least two and a half sensible ways forward:

1. make install do what it claims to do and satisfy the dependencies, turning it into a dependency problem fixing tool it's advertised as
2. change install description to reflect the behaviour, e.g., by adding an "unless the package is installed", or moving the claim about satisfying dependencies to reinstall, which actually does that
2a. if it's not doing anything anyway on the grounds of having the package already installed, maybe also make it skip "Updating and loading repositories" phase while you're at it

**Comment by j-mracek** [comment] 2024-05-29 09:03
If I am not mistaken in past yum-3 did a check for system integrity in background, therefore it allowed to detect such a situation. The question whether we should implement such a mechanism in DNF5? The problem is about price (CPU) where this will be not for free and current implementation of check command is quite slow.

**Comment by jan-kolarik** [comment] 2024-11-26 10:15
The man pages were fixed, I am closing this.

**Closed by jan-kolarik** 2024-11-26 10:15 UTC
Labels: Triaged
