### ISSUE TITLE
filter_requires does not give always the same result in python

### ISSUE THREAD

**Issue by papoteur-mga** [rpm-software-management/dnf5#1358] opened 2024-03-30 10:39 UTC
What I try to do is to get a list of dependencies in the form of package names. 
I see in #1086 that I can use something like: 
```
query = libdnf5.rpm.PackageQuery(base)
deps = []
reqs = last.get_requires()
for item in query.filter_provides(reqs):
                if not item.get_name() in deps:
                    deps.append(item.get_name())
```
I have an instance where this is working, but another one where the result is void. I'm don't understand why.
Major difference is that the first is on my dev laptop in x86_64, when the problematic is RPI 4 on aarch64.
The app is a Flask service, and I run with the Flask dev tool (flask run) on the dev laptop, but with a gunicorn service with 2 workers on the RPI.
The base is not the system one, but a rooted one from Mageia repositories.
dnf5 is installed from [Copr repositories](https://download.copr.fedorainfracloud.org/results/ngompa/dnf5-mga) in Mageia 9

**Comment by j-mracek** [comment] 2024-04-02 08:43
I believe that the problem is related to architecture. Package for x86_64 does not provide anything for arm.

I suggest to set architecture in your script to ansure to get the same result everywhere.

before `base.setup()` set following: base.get_vars

```
       vars = base.get_vars().get()
       vars.set("arch", "x86_64")
       base.setup()
```
This code will prevent a detection of your workers architecture and will use your laptop architecture.

**Comment by papoteur-mga** [comment] 2024-04-03 19:41
Thanks for your interest to this question.
I confirm that the issue is with the arch used for the queries. I used this test case:
```
import os
import libdnf5

from datetime import datetime, timedelta
from libdnf5.common import QueryCmp_GLOB as GLOB
import madb.config as config

MIRROR_URL = "https://fr2.rpmfind.net/linux/mageia/distrib/"

class Dnf5MadbBase(libdnf5.base.Base):

    def __init__(self, release, arch, root, refresh=False):

        self.release = release
        self.arch = arch
        self.root = root

        libdnf5.base.Base.__init__(self)
        # Create a new Base object
        self._base = libdnf5.base.Base()
        self._base_config = self._base.get_config()
        self._base_config.installroot = root
        # https://github.com/rpm-software-management/dnf5/issues/412#issuecomment-1493782078
        self._base_config.optional_metadata_types = ['filelists', 'other']
        self._base.setup()
        self._base.config_file_path = os.path.join(root, "dnf/dnf.conf")
        self._base.load_config()
        vars = self._base.get_vars().get()
        vars.set('releasever', release)
        vars.set('basearch', arch)
        vars.set('arch', arch)
        self._base_config.logdir = os.path.join(root, "dnf","logs")
        vars.set('distarch', arch)
        self._base_config.cachedir = os.path.join(root, "dnf", "cache")
        #self._base_config.reposdir = os.path.join(root, "dnf", "etc","distro.repos.d")
        log_router = self._base.get_logger()
        logger = libdnf5.logger.create_file_logger(self._base)
        log_router.add_logger(logger)
        self._base_config.module_platform_id = f"Mageia:{release}"
        self._base_config.metadata_expire = 20 if refresh else -1
        self._repo_sack = self._base.get_repo_sack()
        repos = {}
        for section in ("core", "nonfree", "tainted"):
            for cl in ("backports", "backports_testing", "release", "updates", "updates_testing"):
                repo_name = f"{release}-{arch}-{section}-{cl}"
                repos[repo_name] = self._repo_sack.create_repo(repo_name)
                repos[repo_name].get_config().baseurl = os.path.join(MIRROR_URL, release, arch, "media", section, cl)
                repos[repo_name].get_config().name = f"Mageia 9 {arch} {section.capitalize()} {cl.capitalize()}"
        print(f"Loading")
        self._repo_sack.update_and_load_enabled_repos(False)


    def provides_requires(self, rpm_list):
        query = libdnf5.rpm.PackageQuery(self._base)
        query.filter_arch([self.arch, "noarch"])
        query.filter_repo_id([self.release + "*"], GLOB)
        query.filter_provides(rpm_list)
        return query


    def search_name(self, values, repo=None):
        """Search in a list of package attributes for a list of keys.

        :param values: the values to match
        :return: a PackageQuery object
        """
        query = libdnf5.rpm.PackageQuery(self._base)
        #query.filter_arch([self.arch, "noarch"])
        query.filter_name(values, GLOB)
        if repo:
            query.filter_repo_id([repo], GLOB)
        return query

release = "9"
arch = "aarch64"
package = "kodi"
repo = "9-aarch64-core-release"
distro = Dnf5MadbBase(release, arch, "/tmp")
dnf_pkgs = distro.search_name([package], repo=repo)
rpms = []
last = None
for dnf_pkg in dnf_pkgs:
    last = dnf_pkg
if last is not None:
    deps = []
    reqs = last.get_requires()
    # logging.debug(f"Requires: {reqs}")
    for item in distro.provides_requires(reqs):
    #    logging.debug(item.get_name())
        if not item.get_name() in deps:
            deps.append(item.get_name())
print(deps)
```
To have the result I expect, I have to use the arch on which the script is running.
On my laptop, intel i7, I have to use arch = "x86_64" or "i586".  With arch = "aarch64", I get only one value, which is not OK.
This is the inverse when running on the RPI 4.
Note that in this example, I have set all vars 'arch', 'basearch', 'distarch'. In my first tests, I had only defined distarch, but the result is the same, even if I define the others with "x86_64".

**Comment by j-mracek** [comment] 2024-04-04 13:47
I believe that `arch` variable is the important one. When basearch is not set, then it is evaluated from `arch`. When arch is not set, then it is detected from the system. 'distarch' is a custom variable that might be used for substitution for paths including `baseurl`, but for your code example it is not important at all. Shall we close the issue as resolved?

**Comment by papoteur-mga** [comment] 2024-04-04 15:58
@j-mracek 
Hi,
I have edited my example with setting only 'arch' variable.
When I run it on my laptop, this is OK with both arches 'aarch64' and 'x86_64'.
But I still have the same problem when running it on RPI. The result is OK when arch is 'aarch64', but not when it is 'x86_64'
Thus, I think there is something weird.

**Comment by j-mracek** [comment] 2024-04-05 09:00
I think that the problem is in `self._base.setup()` that is called too early. It must be called after vars are set.

What about to move it here:
```
        self._base_config.metadata_expire = 20 if refresh else -1
        self._base.setup()
        self._repo_sack = self._base.get_repo_sack()
```

I am also thinking about `class Dnf5MadbBase(libdnf5.base.Base):`
I think that the inheritance is not right. There should be `class Dnf5MadbBase():` and line `libdnf5.base.Base.__init__(self)` should be deleted. In theory you try to initialize two instances, but you need only one from `self._base = libdnf5.base.Base()`.

**Comment by papoteur-mga** [comment] 2024-04-05 18:35
> I think that the problem is in `self._base.setup()` that is called too early. It must be called after vars are set.
> 
> What about to move it here:
> 
> ```
>         self._base_config.metadata_expire = 20 if refresh else -1
>         self._base.setup()
>         self._repo_sack = self._base.get_repo_sack()
> ```

YES, this is the solution! Thanks a lot !

> I am also thinking about `class Dnf5MadbBase(libdnf5.base.Base):` I think that the inheritance is not right. There should be `class Dnf5MadbBase():` and line `libdnf5.base.Base.__init__(self)` should be deleted. In theory you try to initialize two instances, but you need only one from `self._base = libdnf5.base.Base()`.

This is clearer, but this was not the problem.

**Closed** 2024-04-05 18:44 UTC
