### ISSUE TITLE
libdnf5.rpm.Nevra.parse wrong behavior

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1359] opened 2024-03-30 17:25 UTC
If a nevra name has no epoch that should be parsed as "0" and not empty string.

test_code:
```
import libdnf5
pkg = libdnf5.rpm.Nevra.parse("firefox-115.8.0-1.mga9")[0]
epoch = pkg.get_epoch()
print("package name ", pkg.get_name(), " with epoch: ", epoch if epoch else "missing")
```
result:
`package name  firefox  with epoch:  missing`

debug output:
```
(Pdb) p pkg.get_name()
'firefox'
(Pdb) p pkg.get_epoch()
''
```

**Comment by Conan-Kudo** [comment] 2024-03-30 17:31
This is already being discussed elsewhere.

Duplicate of https://github.com/rpm-software-management/dnf5/issues/1175

**Closed by Conan-Kudo** 2024-03-30 17:31 UTC

**Comment by anaselli** [comment] 2024-03-30 17:34
i searched for Nevra didn't think to epoch :)
