### ISSUE TITLE
`--qf` is missing new lines

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/dnf5#1124] opened 2024-01-03 09:55 UTC
~~~
$ dnf4 repoquery -q --disablerepo='*' --enablerepo=rawhide-source --arch=src --qf '%{name}' --whatrequires 'ruby' | head -n 2
bindfs
clearsilver
~~~

vs

~~~
$ dnf repoquery -q --disablerepo='*' --enablerepo=rawhide-source --arch=src --qf '%{name}' --whatrequires 'ruby' | head -n 2
bindfsclearsilverfacterfantasdicgegl04graphvizgroongakf5-kross-interpreterslibcacalibgximliblastfmlibosmiumlibselinuxmigemomltocl-icdopenwsmanpcsplayerpre-commitpuppetqdbmqtwebkitrrdtoolruby-augeasruby-bsearchruby-gnome2ruby-icon-artistruby-mecabruby-romkanrubygem-Ascii85rubygem-abrtrubygem-actioncablerubygem-actionmailboxrubygem-actionmailerrubygem-actionpackrubygem-actiontextrubygem-activejobrubygem-activemodelrubygem-activemodel-serializers-xmlrubygem-activestoragerubygem-activesupportrubygem-acts_as_listrubygem-ammeterrubygem-ansirubygem-apipie-railsrubygem-appraisalrubygem-arubarubygem-asciidoctor-pdfrubygem-async_sinatrarubygem-awesome_printrubygem-backportsrubygem-baconrubygem-base32rubygem-benchmark-ipsrubygem-between_mealsrubygem-builderrubygem-bundlerrubygem-bundler_extrubygem-capybararubygem-chronicrubygem-chunky_pngrubygem-clockworkrubygem-coderayrubygem-colorrubygem-concurrent-rubyrubygem-connection_poolrubygem-contractsrubygem-crassrubygem-css_parserrubygem-cucumberrubygem-cucumber-corerubygem-cucumber-create-metarubygem-cucumber-gherkinrubygem-cucumber-messagesrubygem-cucumber-tag-expressionsrubygem-cucumber-wirerubygem-daemon_controllerrubygem-dallirubygem-deep_mergerubygem-deloreanrubygem-diff-lcsrubygem-diffyrubygem-dnsrubyrubygem-ejsrubygem-elasticsearch-transportrubygem-em-http-requestrubygem-em-specrubygem-em-websocketrubygem-em-websocket-clientrubygem-erubirubygem-ethonrubygem-exconrubygem-factory_botrubygem-fake_ftprubygem-fakefsrubygem-faradayrubygem-fog-corerubygem-fog-jsonrubygem-fog-libvirtrubygem-fog-xmlrubygem-gdk3rubygem-gem-nice-installrubygem-gem2rpmrubygem-gistrubygem-gitrubygem-globalidrubygem-goocanvas1rubygem-gssapirubygem-gtk3rubygem-guardrubygem-guard-compatrubygem-guard-livereloadrubygem-guard-shellrubygem-hamlrubygem-hashdiffrubygem-hasheryrubygem-hashrrubygem-hiera-vaultrubygem-highlinerubygem-hoconrubygem-hrxrubygem-http-acceptrubygem-http_connectionrubygem-httpartyrubygem-i18nrubygem-image_processingrubygem-image_sizerubygem-importmap-railsrubygem-introspectionrubygem-jbuilderrubygem-jekyllrubygem-jekyll-asciidocrubygem-jekyll-email-protectrubygem-jekyll-feedrubygem-jekyll-git-authorsrubygem-jekyll-sass-converterrubygem-jekyll-seo-tagrubygem-jekyll-tocrubygem-jekyll-watchrubygem-kramdown-parser-gfmrubygem-kramdown-syntax-coderayrubygem-launchyrubygem-linked-listrubygem-liquidrubygem-listenrubygem-localerubygem-loofahrubygem-lumberjackrubygem-mailrubygem-marcelrubygem-memfsrubygem-metaclassrubygem-method_sourcerubygem-middlewarerubygem-mime-typesrubygem-mime-types-datarubygem-mimemagicrubygem-mini_magickrubygem-mini_mimerubygem-minimarubygem-minitest-profilerubygem-minitest-stub-construbygem-mixlib-logrubygem-mocharubygem-mongorubygem-mongoidrubygem-multi_jsonrubygem-multi_testrubygem-multi_xmlrubygem-multipart-postrubygem-mustacherubygem-mustermannrubygem-ncurseswrubygem-nestyrubygem-net-sftprubygem-net-sshrubygem-netrcrubygem-niftirubygem-notiffanyrubygem-parallelrubygem-parse-cronrubygem-pastelrubygem-pdf-corerubygem-pdf-inspectorrubygem-pdf-readerrubygem-polyglotrubygem-prawnrubygem-prawn-iconrubygem-prawn-svgrubygem-prawn-tablerubygem-prawn-templatesrubygem-progressbarrubygem-pryrubygem-pry-byebugrubygem-public_suffixrubygem-punditrubygem-puppet-lintrubygem-puppet-resource_apirubygem-rackrubygem-rack-cacherubygem-rack-protectionrubygem-rack-restful_submitrubygem-rack-testrubygem-railsrubygem-rails-controller-testingrubygem-rails-deprecated_sanitizerrubygem-rails-dom-testingrubygem-rails-html-sanitizerrubygem-railtiesrubygem-rainbowrubygem-rakerubygem-rake-contribrubygem-rb-inotifyrubygem-rbvmomirubygem-rchardetrubygem-rdocrubygem-red-colorsrubygem-redisrubygem-redis-clientrubygem-refrubygem-regexp_parserrubygem-require_allrubygem-rest-clientrubygem-rgenrubygem-rmailrubygem-ronn-ngrubygem-rrrubygem-rspec-railsrubygem-ruby-dbusrubygem-ruby-libvirtrubygem-ruby-progressbarrubygem-ruby-rc4rubygem-ruby-vipsrubygem-rubygems-mirrorrubygem-rubyziprubygem-ruggedrubygem-sass-railsrubygem-sassc-railsrubygem-scanfrubygem-sd_notifyrubygem-selenium-webdriverrubygem-sequelrubygem-settingslogicrubygem-shindorubygem-shoulda-contextrubygem-shoulda-matchersrubygem-simplecovrubygem-simplecov-htmlrubygem-simpleidnrubygem-sinatrarubygem-slimrubygem-snmprubygem-springrubygem-sprocketsrubygem-sprockets-railsrubygem-stringexrubygem-syckrubygem-syncrubygem-sys-unamerubygem-systemurubygem-templerubygem-term-ansicolorrubygem-terminal-tablerubygem-test_constructrubygem-test_declarativerubygem-thorrubygem-tiltrubygem-timersrubygem-tinsrubygem-tomlrbrubygem-treetoprubygem-ttfunkrubygem-tty-colorrubygem-turbolinksrubygem-turbolinks-sourcerubygem-typhoeusrubygem-tzinforubygem-vaultrubygem-web-consolerubygem-webkit2-gtkrubygem-webmockrubygem-webrickrubygem-websocketrubygem-websocket-extensionsrubygem-xml-simplerubygem-xmlparserrubygem-xmlrpcrubygem-yardrubygem-zeitwerksimsparkstflsubversiontmateuwsgivagrantvagrant-cachiervagrant-digitaloceanvagrant-hostmanagervagrant-openstack-providervimwebkit2gtk4.0webkitgtkweechatxapian-bindingsxmms2
~~~

**Comment by voxik** [comment] 2024-01-03 09:56
This can be workaround by `--qf '%{name}\n'

**Comment by kontura** [comment] 2024-01-03 10:21
This is a duplicate of https://github.com/rpm-software-management/dnf5/issues/709

**Closed by kontura** 2024-01-03 10:21 UTC
