### ISSUE TITLE
Dnf5 fails to install @buildsys-build group

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#254] opened 2023-01-27 08:03 UTC
/bin/dnf works fine:

```
[root@f69e312fadf3 /]# dnf install @buildsys-build
Last metadata expiration check: 0:02:24 ago on Fri Jan 27 07:57:23 2023.
Dependencies resolved.
===========================================================================
 Package      Architecture   Version                 Repository       Size
===========================================================================
Installing group/module packages:
 info         x86_64         7.0.2-1.fc38            rawhide         181 k
Installing Groups:
 Buildsystem building group
                                                                          

Transaction Summary
===========================================================================
Install  1 Package

Total download size: 181 k
Installed size: 370 k
Is this ok [y/N]: n
```

while dnf5 doesn't see the group

```
Operation aborted.
[root@f69e312fadf3 /]# dnf5 install @buildsys-build
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: @buildsys-build
```

Is there a way around? [This complicates Mock+DNF5 experiments](https://github.com/rpm-software-management/mock/pull/1027)

```
[root@f69e312fadf3 /]# rpm -q dnf5 dnf5-plugins dnf
dnf5-5.0.4-3.fc38.x86_64
dnf5-plugins-5.0.4-3.fc38.x86_64
dnf-4.14.0-2.fc38.noarch
```

**Comment by j-mracek** [comment] 2023-01-27 09:12
Thank you very much for the report. The issue is fixed in dnf5-5.0.5, that was released yesterday in upstream - https://bodhi.fedoraproject.org/updates/FEDORA-2023-c7d282fcb0.

**Closed by j-mracek** 2023-01-27 09:12 UTC
