### ISSUE TITLE
upgrade vs. update

### ISSUE THREAD

**Issue by mattdm** [rpm-software-management/dnf5#441] opened 2023-04-07 21:59 UTC
Synopsis
------------

I suggest consistently using `update` to mean _update packages to latest version_ and `upgrade` to mean "update the entire Distro release" — but keeping the aliases as they are for convenience.

Reason
-----------

In Fedora, we consistently use the word "upgrade" to mean going from one release version to the next.

GNOME Software likewise uses "updates", not "upgrades" for package updates.

DNF's usage is quirky and inconsistent.

Background
---------------

I know sometime in the distant past (possibly in `yum` days?) there was a switch from `update` to `upgrade` as the "main" command for updating packages. If I remember right, this is partly because `apt upgrade` updates all packages — but that's because `apt update` means "update just the metadata". Yum and DNF have never worked that way. 

I think it's more important to be consistent with the way we talk about things in the Fedora universe than to keep that not-really-the-same-anyway parallel to apt.

Specifically...
-----------------

* The main command now called `upgrade` should be `update`.
* We should talk "updates" and "updating" in the documentation and guides.
* `upgrade` should be an alias for `upgrade` so as not to break people.
* `up` should _definitely_ still be an alias, because it's short!

* `offline-upgrade` should become `offline-update` — again with an alias.
* I think `system-upgrade` should _also_ become an alias of `offline-update` — with presence of `--releasever` making the difference.

**Comment by mcurlej** [comment] 2023-04-17 12:28
Hi @mattdm, AFAIK historically there where changes made when dnf replaced yum. Yum had some differences in those arguments. For the current DNF 4 implementation and the future DNF 5 implementation the "correct" term is `upgrade`. This term is also used in the code and when talking about upgrading packages to another version. `update` is now used only as an alias for the `upgrade` argument. In DNF 5 the bash completion only provides the `upgrade` argument by default to reinforce the usage for the future. Unfortunately, as you are also stating, we need to keep aliases as `update` for legacy deployments of our users. For the nearest future we are not planning to make changes to the `upgrade` argument, but we can go through our documentation to see if there are not some inconsistencies with regards to the naming.

**Comment by mattdm** [comment] 2023-04-17 21:49
I hope you can see how, from the point of view of a distribution, the word `upgrade` is confusing. I just checked the [RHEL 9 docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool/assembly_updating-rhel-9-content_managing-software-with-the-dnf-tool), and while they do use `dnf upgrade`:

* the section where that is described is called "Updating packages"
* the text under that consistently says "update" ("to update all packages", "to update a single package", etc.)

I know it's not the biggest thing in the world, but the dissonance is apparent. And it seems like 4 -> 5 is one of the few opportunities to straighten this out and make it so the command used matches the language.

**Comment by j-mracek** [comment] 2023-04-18 05:54
The problem from DNF perspective - DNF does not know whether operation will result in small update or a bigger upgrade. DNF only sees arguments. There is one exception - using `system-upgrade` command. This command was designed to jump from one major version to another one. 

`dnf system-upgrade --releasever=38` is very similar to `dnf distrosync  --releasever=38`
`dnf system-upgrade --releasever=38 --no-downgrades` is very similar to `dnf upgrade|update  --releasever=38`

In past (yum in rhel7) - we introduced `upgrade` and `update` with a different behavior. `yum upgrade` was stronger, because it followed obsoletes. In DNF - both command has identical behavior, because there is configuration option for the behavior. By default DNF behaves like `yum upgrade` therefore DNF uses as primary name for the command `upgrade` name.

**Comment by pirat89** [comment] 2023-06-08 20:19
Thanks @j-mracek  for the explanation. I see the logic behind the current state.

However I have to say that it would be nice to make it clear what is `update` and `upgrade` as it could be confusing really for people and our customers. "Many" customers are now making differences between update and upgrade following the definition @mattdm  used in the description - not sure how many, but some our partners use these terms in this way and I know it has been also presented at least couple of times to understand these words in this way. Based on that, we put these definitions also to our [in-place upgrades documentations for RHEL systems](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#ref_key-migration-terminology_upgrading-from-rhel-7-to-rhel-8)

I am not saying that one is totally better than the other. tbh, I preferred/suggested to use always term  `in-place upgrade` as the shortest variant for our projects. However it evolved in this form over years as `upgrade` vs `in-place upgrade` have been confusing for people as they naturally wanted to switch to typical `upgrade` term. So it evolved into `update` vs `upgrade` terminology over years. Not saying what should be the decision, just adding my $0.02 for the discussion.

**Comment by praiskup** [comment] 2023-06-09 06:16
Can we have a manpage documentation section like *history of the `update` and `upgrade` commands*?  Together with the `dnf upgrade` alias, these could be the last occurrences of the `upgrade` term in the DNF5 code.

**Comment by j-mracek** [comment] 2023-06-12 08:09
The behavior change is already described in https://dnf.readthedocs.io/en/latest/cli_vs_yum.html#update-and-upgrade-commands-are-the-same. Therefore this is not something to document in a section describing changes in dnf5.

**Comment by j-mracek** [comment] 2023-08-07 10:30
I am thinking that the discussion in issue is complete, therefore I am closing the issue.

**Closed** 2023-08-07 10:31 UTC
