### ISSUE TITLE
Strange string at the end of transaction

### ISSUE THREAD

**Issue by geraldosimiao** [rpm-software-management/dnf5#1920] opened 2024-12-03 15:44 UTC
At fedora, using dnf5-5.2.7.0-1.fc41.x86_64, we see a strange string at the end of transactions. In en-us it states "Complete!ng" and other languages too, for example pt-br it is "Terminado!ando". 
Oddly the pt-br translation team can't find it at weblate, where's this string came from?

![Screenshot_20241203_123608](https://github.com/user-attachments/assets/bd73158c-0264-4586-ba54-0026e32bbd54)

![Screenshot_20241202_122145](https://github.com/user-attachments/assets/2e933ac6-9b3f-41e1-9b61-aa1cd61aadab)

**Comment by geraldosimiao** [comment] 2024-12-03 16:02
Ohh it seems this is duplicated, here's the first ticket #1899

**Comment by ppisar** [comment] 2024-12-03 16:17
Yes, it's a duplicate of #1899.

**Closed by ppisar** 2024-12-03 16:17 UTC
