### ISSUE TITLE
dnf5 repoquery writes repo update output to stdout not stderr

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/dnf5#1361] opened 2024-04-01 10:38 UTC
Unlike dnf4, `dnf5 repoquery` outputs repo metadata update output to stdout, so it gets prepended to repoquery output, which is pretty bad.

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=2223347

```shellsession
$ dnf5 -q --refresh rq rawhide xz 2>/dev/null 
 Fedora - Rawhide - Developmental packages for the next Fedora release                      100% |  33.6 KiB/s |  40.4 KiB |  00m01s
 Fedora - Rawhide - Developmental packages for the next Fedora release                      100% | 247.8 KiB/s | 488.2 KiB |  00m02s
xz-1:5.4.6-3.fc41.x86_64
```

Note that even --quiet does not prevent the output

**Comment by ppisar** [comment] 2024-04-04 07:28
Original Fedora bug report is <https://bugzilla.redhat.com/show_bug.cgi?id=2172868>.

**Comment by kontura** [comment] 2024-06-07 07:26
The broken `--quiet` option should be fixed by: https://github.com/rpm-software-management/dnf5/commit/328dcead80a3cb611ef551e1768f059a54ee190d now it should hide also the repo metadata update output.

**Comment by jan-kolarik** [comment] 2024-08-20 07:50
Getting back to this.

As @kontura mentioned, using the `-q` or `--quiet` option now suppresses the repository metadata update messages.

Regarding sending repository metadata update messages to standard output, POSIX specifies that conventional output goes to stdout, while diagnostics go to stderr. In my opinion, keeping the user informed about the current action fits the conventional output category, so this approach seems appropriate.

For machine-parsable output, repoquery already supports this via the `--queryformat` option, allowing you to customize the output format, e.g., `dnf5 repoquery -q --queryformat "machine_out: %{full_nevra}\n"`.

Therefore, I'm closing this issue and consider it resolved.

**Comment by hroncok** [comment] 2024-08-20 09:46
This behavior is unexpected and unpleasant to work with. "conventional output" is the result of the query. "repository metadata update messages" is diagnostics/progress.

The mere availability of `machine_out` queryformat does not make this not a bug.

**Comment by keszybz** [comment] 2024-08-20 13:51
What Miro said. This is just broken. It's certainly possible to work around the issue, but as multiple people who need to use this interface for scripting have said, the current way how the output is split is annoying and hard to use.

**Comment by jan-kolarik** [comment] 2024-08-20 13:57
> This behavior is unexpected and unpleasant to work with. 

... snip ...

> This is just broken. It's certainly possible to work around the issue, but as multiple people who need to use this interface for scripting have said, the current way how the output is split is annoying and hard to use.

Understood. We'll look into it.

**Closed** 2024-09-02 15:02 UTC
Labels: Priority: HIGH, bug, Triaged
