### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by manisandro** [rpm-software-management/dnf5#1550] opened 2024-06-14 20:46 UTC
As initially filed at https://bugzilla.redhat.com/show_bug.cgi?id=2282104:

I ran dnf update, and ran out of space while the scriptlets where running

```
$ sudo dnf update
[...]
>>> Stop trigger-post-uninstall scriptlet: man-db-0:2.12.1-1.fc41.x86_64SQL statement execution failed: "ROLLBACK": (1) - SQL logic error
```

Any subsequent dnf update now fails with:

```
$ sudo dnf update
terminate called after throwing an instance of 'std::out_of_range'
  what():  [error] key "reason" not found
 --> /usr/lib/sysimage/libdnf5/packages.toml
      |
 9464 | [packages."zeromq.x86_64"]
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~ in this table
Aborted
```

Reproducible: Always

dnf5-5.2.1.0-1.fc41.x86_64

The `out_of_range` exception persists with
dnf5-5.2.3.0-3.fc41.x86_64

**Comment by m-blaha** [comment] 2024-08-05 07:31
The problem is that TOML files in `/usr/lib/sysimage/libdnf5/*.toml` (or at least some of them) are not parsable. Most likely their content is incomplete due to running out of the disk space. The immediate help to make dnf5 working again would be removing (or backuping) them.

The real solution needs to be on several layers:

1. do not terminate in such situation, print an error message instead (this will be fixed in this ticket)
2. we can try to make system state writing more robust (e.g. write the toml files to temporary location first and then move them to the final one to prevent ending up with partial files) - new issue https://github.com/rpm-software-management/dnf5/issues/1609
3. we need a recover mechanism - something like `dnf5 system-state regenerate` command which would regenerate as much of system state as possible from rpmdb and dnf5 transaction history database - new issue https://github.com/rpm-software-management/dnf5/issues/1610

**Closed** 2024-08-22 04:46 UTC
Labels: Priority: HIGH, bug, Triaged
