### ISSUE TITLE
Improve reporting RPM errors

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#1709] opened 2024-09-19 07:30 UTC
This is a follow-up to the original dnf4 request from https://bugzilla.redhat.com/show_bug.cgi?id=2312906.

Sometimes we report a generic RPM error, even though RPM can provide a more detailed, descriptive message.

```
[3/4] Upgrading filesystem-0:3.18-23.fc41.x86_64                                                 100% |   1.5 MiB/s | 212.5 KiB |  00m00s
>>> Unpack error: filesystem-0:3.18-23.fc41.x86_64

Transaction failed: Rpm transaction failed.
```

While with the old `yum`:

```
"unpacking of archive failed on file /media: cpio: lsetfilecon"
```

Related: https://bugzilla.redhat.com/show_bug.cgi?id=1878057.
Related: https://github.com/rpm-software-management/dnf5/issues/849#issuecomment-1991314680

**Comment by ppisar** [comment] 2024-09-20 08:18
Duplicate of #1710.

**Closed by ppisar** 2024-09-20 08:18 UTC
