### ISSUE TITLE
dnf progress output is messy without a terminal

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#692] opened 2023-06-30 21:04 UTC
When running the lorax tests in CI (or podman via `make test-in-podman`) the progress output is missing \n so it all ends up jumbled together and hard to read. I also tried adding --quiet but that didn't change the output at all.

For comparison the old output looked like this:
https://github.com/weldr/lorax/actions/runs/5297278368/jobs/9588953618

which has everything nice and readable.

The new output looks ok up to the point where it is printing the progress:
https://github.com/weldr/lorax/actions/runs/5426938047/jobs/9869627355

**Comment by j-mracek** [comment] 2023-08-23 15:13
Increasing the priority because of additional report.

**Comment by voxik** [comment] 2023-08-23 20:00
Please note that this is not just about end of lines, but also ton of lines reporting download progress.

**Comment by j-mracek** [comment] 2023-12-06 13:04
The issue is a duplicate of https://github.com/rpm-software-management/dnf5/issues/1058

**Comment by j-mracek** [comment] 2023-12-07 08:54
Closing it as a duplicate

**Closed by j-mracek** 2023-12-07 08:54 UTC
Labels: Priority: MEDIUM, Triaged
