### ISSUE TITLE
[Clone of DNF issue #1968] DNF shows no information but prompts for Y/N when quiet option is set

### ISSUE THREAD

**Issue by sshedi** [rpm-software-management/dnf5#787] opened 2023-08-02 02:22 UTC
This issue is a clone of https://github.com/rpm-software-management/dnf/issues/1968
Created this in dnf5 as suggested by @inknos.

Using the same description here as well.

Hi DNF maintainers,

Please consider this as an investigation question out of curiosity. When I pass -q with install, erase commands; dnf simply asks Y/N.

➜ $ sudo dnf install vsftpd -q
Is this ok [y/N]:
As an end user, I don't know what is happening here in the background is and should I say yes or no.
Is this intended or some historical reason behind this decision?

My expectation here is:

Either abort the operation saying quiet is set but no assumeyes or assumeno given.
OR, ignore -q and print everything when command is something other than clean or mackecache.
Please feel free to correct me if my understanding is wrong here. Thanks.

**Comment by j-mracek** [comment] 2023-08-07 08:05
The issue is related to https://github.com/rpm-software-management/dnf5/issues/570. The expectations there differs from yours. I propose to close this issue as a duplicate. What do you think @sshedi ?

**Comment by sshedi** [comment] 2023-08-07 10:49
I suggested two ways to fix this. Please check the end part of the issue description.

Also, specifying `-q` without assume yes/no is a user error. So, dnf should inform about it and stop.

**Comment by sshedi** [comment] 2023-08-07 10:52
I'm okay with closing this bug but the fix for this should be what is right and not what user expects it to be.

Simple showing a yes or no prompt with no context doesn't look right to me.
Thanks for your response and please feel free to close this issue.

**Comment by j-mracek** [comment] 2023-08-08 06:04
I am closing it as a duplicate

**Closed by j-mracek** 2023-08-08 06:04 UTC
