### ISSUE TITLE
Plugin API roadmap

### ISSUE THREAD

**Issue by gordonmessmer** [rpm-software-management/dnf5#259] opened 2023-01-31 03:41 UTC
I'm working on integration between dnf4 and PackageKit, and I'd like to make sure that integration with dn5 is ready before Fedora swaps the default dnf.  Is there any documentation for the new plugin API?  Any roadmap that might provide an estimate of when the plugin API will be stable?

**Comment by j-mracek** [comment] 2023-02-14 07:23
This is a good question. Right now we are stabilizing API according to feedback from other project that started with adoption of DNF5. Therefore if you wait until the API is fully stable and then you will have to propose the changes in our API to satisfy your project requirements. To ensure that we are not braking your project I recommend to include your project in our CI. Then we could fix your project at the time of the change. I believe that API will be fully stable in June, but as I said it depends on other team requests. Is it what you need to know?

**Comment by j-mracek** [comment] 2023-09-13 06:01
From dnf5-5.1 API is marked as stable. If we will need to modify API, we will mark method as deprecated first and then there will be a period when the method will be available. The final step - removal will be not performed in stable releases.

I guess that the issue is resolved therefore I am closing it.

**Closed by j-mracek** 2023-09-13 06:01 UTC
