### ISSUE TITLE
dnf update: Excessive "replacement" spam

### ISSUE THREAD

**Issue by farchord** [rpm-software-management/dnf5#1535] opened 2024-06-06 19:02 UTC
On DNF5, it seems every package getting updated is considered as a replacement. Before, on dnf4, it would only show that it's replacing if package X was being superceded by package Y.

This is an example of the update log on Fedora 41 (Rawhide):

![Screenshot_20240606_150326](https://github.com/rpm-software-management/dnf5/assets/1653443/25070f56-9acb-4d24-8829-1677490dfb24)

dnf5 version 5.2.3.0
dnf5 plugin API version 2.0
libdnf5 version 5.2.3.0
libdnf5 plugin API version 2.0

Loaded dnf5 plugins:
  name: builddep
  version: 1.0.0
  API version: 2.0

  name: changelog
  version: 1.0.0
  API version: 2.0

  name: config-manager
  version: 0.1.0
  API version: 2.0

  name: copr
  version: 0.1.0
  API version: 2.0

  name: needs_restarting
  version: 1.0.0
  API version: 2.0

  name: repoclosure
  version: 1.0.0
  API version: 2.0

**Comment by ppisar** [comment] 2024-06-07 08:10
Duplicate of #326.

**Closed by ppisar** 2024-06-07 08:10 UTC
