### ISSUE TITLE
Optimizing output?

### ISSUE THREAD

**Issue by birdie-github** [rpm-software-management/dnf5#1898] opened 2024-11-25 14:38 UTC
When updating F41 you see this:
```
Package                      Arch   Version                 Repository      Size
Upgrading:
 efi-filesystem              noarch 5-13.fc41               updates      0.0   B
   replacing efi-filesystem  noarch 5-12.fc41               fedora       0.0   B
 efi-srpm-macros             noarch 5-13.fc41               updates     40.2 KiB
   replacing efi-srpm-macros noarch 5-12.fc41               fedora      40.1 KiB
 qemu-img                    x86_64 2:9.1.2-1.fc41          updates     22.9 MiB
   replacing qemu-img        x86_64 2:9.1.1-2.fc41          updates     22.9 MiB
 unbound-libs                i686   1.22.0-8.fc41           updates      1.5 MiB
   replacing unbound-libs    i686   1.21.1-1.fc41           fedora       1.5 MiB
 unbound-libs                x86_64 1.22.0-8.fc41           updates      1.4 MiB
   replacing unbound-libs    x86_64 1.21.1-1.fc41           fedora       1.4 MiB
```

Could we go back to how DNF worked and that is only showing replacements when there's a package with a new name replacing an old one?

E.g.

```
Package                      Arch   Version                 Repository      Size
Upgrading:
 efi-filesystem              noarch 5-13.fc41               updates      0.0   B
 efi-srpm-macros             noarch 5-13.fc41               updates     40.2 KiB
 qemu-img                    x86_64 2:9.1.2-1.fc41          updates     22.9 MiB
 unbound-libs                i686   1.22.0-8.fc41           updates      1.5 MiB
 unbound-libs                x86_64 1.22.0-8.fc41           updates      1.4 MiB
```

or

```
Package                      Arch   Version                           Repository      Size
Upgrading:
 efi-filesystem              noarch 5-12.fc41      ->      5-13.fc41   updates      0.0   B
 efi-srpm-macros             noarch 5-12.fc41      ->      5-13.fc41   updates     40.2 KiB
 qemu-img                    x86_64 2:9.1.1-2.fc41 -> 2:9.1.2-1.fc41   updates     22.9 MiB
 unbound-libs                i686   1.21.1-1.fc41  ->  1.22.0-8.fc41   updates      1.5 MiB
 unbound-libs                x86_64 1.21.1-1.fc41  ->  1.22.0-8.fc41   updates      1.4 MiB
```

**Comment by ppisar** [comment] 2024-11-29 11:18
Duplicate of issue #326.

**Closed by ppisar** 2024-11-29 11:18 UTC
Labels: duplicate, Triaged
