### ISSUE TITLE
Implement additional repoquery options

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#122] opened 2022-11-07 08:55 UTC
The [dnf4 repoquery command](https://dnf.readthedocs.io/en/latest/command_ref.html#repoquery-command-label) has a lot of options.

There are two categories:
### Select Options
_Together with the \<package-file-spec\> argument, control what packages are displayed in the output._
- [x] \<package-file-spec\>
- [x] -a, --all
- - Proposing to drop it (document as a change). It is a default dnf behavior and it was added as compatibility option with yum

- [x] --arch / --archlist
- - Please change other command that uses the same o similar options (even option can be the same, but schematic of arguments can be different) in DNF and unify it
- [x] --duplicates
- [x] #454
- [x] --available
- [x] --disable-modular-filtering
- [x] --extras
- [x] -f \<file\>, --file \<file\>
- [x] --installed
- [x] --installonly
- [x] --latest-limit \<number\>
- [x] --recent
- - Priority low
- [x] --repo \<repoid\>
- - It is a general option. Investigate why it is explicitly mentioned in repoquery
- - [amatej] The best I can tell the option got imported together with repoquery command into dnf. Perhaps before when repoquery was separate the option was needed.
- [x] --upgrades
- [x] --userinstalled
- [x] --whatdepends \<capability\>[,\<capability\>...]
- [x] --whatconflicts \<capability\>[,\<capability\>...]
- [x] --whatenhances \<capability\>[,\<capability\>...]
- [x] --whatobsoletes \<capability\>[,\<capability\>...]
- [x] --whatprovides \<capability\>[,\<capability\>...]
- [x] --whatrecommends \<capability\>[,\<capability\>...]
- [x] --whatrequires \<capability\>[,\<capability\>...]
- [x] --whatsuggests \<capability\>[,\<capability\>...]
- [x] --whatsupplements \<capability\>[,\<capability\>...]
- [x] --alldeps
- - It is a default behavior of DNF therefore I propose to remove it (document the change). The reason of presence of the option -> the default was changed in history
- [x] --exactdeps
- [x] --srpm
- - Please verify that other commands use --srpm, or --source using the same principle

### Formatting Options
_Set what information is displayed about each package._
- [x] #479
- [x] -l, --list
- - Proposing to rename to more appropriate --files
- [x] -s, --source
- - Please verify that other commands use --srpm, or --source using the same principle
- [x] --changelogs
- [x] --conflicts
- [x] --depends
- [x] --enhances
- [x] --location
- [x] --obsoletes
- [x] --provides
- [x] --recommends
- [x] --requires
- [x] --requires-pre
- [x] --suggests
- [x] --supplements
- [x] --nvr
- - Proposing to drop it (document as a change) (yum compatibility)
- [x] --nevra
- - Proposing to drop it (document as a change) (yum compatibility) - default behavior
- [x] --envra
- - Proposing to drop it (document as a change) (yum compatibility) - DNF is unable to parse such a spec
- [x] --qf <format>, --queryformat \<format\>
- - Priority medium (required by fedora-review)

**Additional options:**
- [x] --querytags
- [x] ~~\-\-groupmember \<package-spec\>~~ -> move to `group` command `--contains-pkgs <pkg>` option?
- - moving to group command is a good suggestion. Please document it to DNF to DNF5 changes

**Additional tasks:**
- [x] Add option conflicts (if/where needed)
- [x] Enable autocomplete
- [x] Add man pages/documentation
- [x] Enable CI tests

Options tracked in separate issues:
- [ ] #910
- [ ] #911
- [ ] #912
- [ ] #913
- - Priority low
- - [amatej] Perhaps this would be better suited as a plugin?
- [ ] #914
- - [amatej] Perhaps this would be better suited as a plugin?

**Comment by glum23** [comment] 2023-04-25 12:53
While --qf / --queryformat is marked as implemented, it does not work as expected (namely in RHEL, dnf5-5.0.9-1.git.966.354f7b6.el9). --queryformat provides nothing while --qf is reported to be an unknown option. Comparison with dnf4 results on the same machine is provided:
~~~
# dnf5 repoquery --queryformat='%{name}-%{version}' bash
Updating and loading repositories:
Repositories loaded.
# dnf5 repoquery --qf='%{name}-%{version}' bash
Unknown argument "--qf=%{name}-%{version}" for command "repoquery". Add "--help" for more information about the arguments.
# dnf repoquery --queryformat='%{name}-%{version}' bash
Last metadata expiration check: 1:56:25 ago on Tue 25 Apr 2023 06:50:19 AM EDT.
bash-5.1.8
# dnf repoquery --qf='%{name}-%{version}' bash
Last metadata expiration check: 1:56:48 ago on Tue 25 Apr 2023 06:50:19 AM EDT.
bash-5.1.8
~~~

**Comment by kontura** [comment] 2023-05-02 11:57
The alias for `--qf` is missing but the output should work.
Maybe the output is just overlooked, there was a change where dnf5 no longer automatically adds a new line at the end.
Can you try:
```
dnf5 repoquery --queryformat='%{name}-%{version}\n' bash

```

**Comment by glum23** [comment] 2023-05-03 08:06
@kontura, it's really strange, below is output from terminal (with intentionally deleted some of non-related parts). For the first time 'dnf5 repoquery' is called there's apparently no output related to queryformat, however, there is missing also 'Repositories loaded.' phrase. Every other call shows the requested output (either with \n or without it). Maybe there's some issue related to repos and the first call just fails to provide the whole output, so it's unrelated to repoquery subcommand itself.
dnf5-5.0.9-1.git.966.354f7b6.el9.x86_64
~~~
[root@<deleted> ~]# dnf5 repoquery --queryformat='%{name}-%{version}' bash
Updating and loading repositories:
 Beaker harness                         100% | 267.6 KiB/s |  26.8 KiB |  00m00s
 Beaker Client - RedHatEnterpriseLinux9 100% |  65.3 KiB/s |   5.8 KiB |  00m00s
<deleted part of repo list>
 rhel-SAP-debuginfo                     100% | 269.3 KiB/s |   3.8 KiB |  00m00s
 rhel-SAPHANA-debuginfo                 100% | 214.5 KiB/s |   3.4 KiB |  00m00s
[root@<deleted> ~]# dnf5 repoquery --queryformat='%{name}-%{version}\n' bash
Updating and loading repositories:
Repositories loaded.
bash-5.1.8
[root@<deleted> ~]# dnf5 repoquery --queryformat='%{name}-%{version}' bash
Updating and loading repositories:
Repositories loaded.
bash-5.1.8[root@<deleted> ~]# dnf5 clean all
Removed 88 files, 66 directories. 0 errors occurred.
[root@<deleted> ~]# dnf5 repoquery --queryformat='%{name}-%{version}' bash
Updating and loading repositories:
 Beaker harness                                        100% | 265.0 KiB/s |  26.8 KiB |  00m00s
 Beaker Client - RedHatEnterpriseLinux9                100% |  64.6 KiB/s |   5.8 KiB |  00m00s
<deleted part of repo list>
 rhel-NFV-debuginfo                                    100% | 193.2 KiB/s |   2.9 KiB |  00m00s
 rhel-SAPHANA                                          100% | 331.2 KiB/s |   6.6 KiB |  00m00s
Repositories loaded.
bash-5.1.8[root@<deleted> ~]#
~~~

**Comment by kontura** [comment] 2023-05-06 17:51
@glum23 can I please ask you to file a separate bug about that?

**Comment by glum23** [comment] 2023-05-09 12:15
The bug can be reproduced only in rhel9, postponed until the next build of dnf5 for rhel9.

**Comment by davide125** [comment] 2023-06-22 07:05
`fedora-review` is breaking in Rawhide because `dnf repoquery -C` isn't implemented.

**Comment by kontura** [comment] 2023-06-22 08:25
> `fedora-review` is breaking in Rawhide because `dnf repoquery -C` isn't implemented.

It is a general dnf option, tracked here: https://github.com/rpm-software-management/dnf5/issues/191

**Comment by jan-kolarik** [comment] 2023-06-22 10:45
> `fedora-review` is breaking in Rawhide because `dnf repoquery -C` isn't implemented.

I've added this request to the tracking issue here: https://github.com/rpm-software-management/dnf5/issues/635.

**Comment by FrostyX** [comment] 2023-07-25 19:33
> fedora-review is breaking in Rawhide because dnf repoquery -C isn't implemented.

It is failing because of the missing `--resolve` parameter as well.

**Comment by j-mracek** [comment] 2023-09-25 12:19
I excluded remaining options into separate issue to allow testing of implemented featires

**Closed by j-mracek** 2023-09-25 12:19 UTC
Labels: RFE, Priority: HIGH, Triaged
