### ISSUE TITLE
dnf5 tool does not translate messages (missing setlocale()?)

### ISSUE THREAD

**Issue by goeranu** [rpm-software-management/dnf5#1375] opened 2024-04-03 20:03 UTC
Although there is a `/usr/share/locale/sv/LC_MESSAGES/dnf5.mo` included in dnf5-5.1.15-1.fc40.x86_64, there interface does still not seem to be translated at all. The Weblate status have been fully translated (it currently needs further updates) but I can't seem to find any translated message when running with `$LANG` set to `sv_SE.utf8`.

**Comment by ppisar** [comment] 2024-04-04 11:11
I confirm that with dnf5-5.1.17-1.fc41.x86_64:

~~~~
LC_ALL=sv_SE.utf8 dnf5 advisory --help
Usage:
  dnf5 [GLOBAL OPTIONS] advisory <COMMAND> ...
                                
Query Commands:                 
  list                          List advisories
  info                          Print details about advisories
  summary                       Print summary of advisories
~~~~

does not localize "List advisories" message which is fully translated in dnf5/po/sv.po:

~~~~
#: commands/advisory/advisory_list.hpp:33
msgid "List advisories"
msgstr "Lista rekommendationer"
~~~~

**Comment by ppisar** [comment] 2024-04-04 11:21
I think a cause is that neither dnf5 tool, nor dnf5-cli library call setlocale():

~~~~
$ git grep setlocale
dnf5daemon-client/context.cpp:    cfg["locale"] = setlocale(LC_MESSAGES, nullptr);
dnf5daemon-client/main.cpp:    setlocale(LC_ALL, "");
test/libdnf5-cli/utils/test_utf8.cpp:    setlocale(LC_ALL, "C.UTF-8");
~~~~

**Comment by j-mracek** [comment] 2024-04-18 08:37
I believe that the issue is resolved in upstream by https://github.com/rpm-software-management/dnf5/pull/1408.

**Closed by j-mracek** 2024-04-18 08:37 UTC
Labels: Priority: MEDIUM, Triaged
