### ISSUE TITLE
Perl bindings FTBFS on 32-bit architectures on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#746] opened 2023-07-20 10:59 UTC
On 32-bit ARM and x86 architectures, the Perl bindings fail to build with the following error:

```
[  258s] [ 41%] Building CXX object bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o
[  258s] cd /home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build/bindings/perl5/libdnf5 && /usr/bin/c++ -DPROJECT_BINARY_DIR=\"/home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build\" -DPROJECT_SOURCE_DIR=\"/home/abuild/rpmbuild/BUILD/dnf5-5.1.0\" -DPROJECT_VERSION_MAJOR=5 -DPROJECT_VERSION_MINOR=1 -DPROJECT_VERSION_PATCH=0 -Dperl5_common_EXPORTS -I/home/abuild/rpmbuild/BUILD/dnf5-5.1.0/include -I/home/abuild/rpmbuild/BUILD/dnf5-5.1.0/common -I/usr/lib/perl5/5.36.1/i586-linux-thread-multi/CORE -fomit-frame-pointer -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -O2 -g -DNDEBUG -std=gnu++20 -fPIC -fmacro-prefix-map=/home/abuild/rpmbuild/BUILD/dnf5-5.1.0/= -Wall -Wextra -Werror -Wcast-align -Wformat-nonliteral -Wmissing-format-attribute -Wsign-compare -Wuninitialized -Wwrite-strings -Werror=unused-result -Wodr -Wconversion -Wl,--as-needed -D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=3 -Wno-cast-align -Wno-conversion -Wno-deprecated-copy -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-missing-declarations -Wno-missing-field-initializers -Wno-sign-compare -Wno-sometimes-uninitialized -Wno-strict-aliasing -Wno-unused-function -Wno-unused-parameter -Wno-catch-value -Wno-maybe-uninitialized -Wno-volatile -MD -MT bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o -MF CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o.d -o CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o -c /home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx
[  258s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx: In function 'int SWIG_AsVal_long_SS_long(SV*, long long int*)':
[  258s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2161:36: error: comparison is always true due to limited range of data type [-Werror=type-limits]
[  258s]  2161 |     if (UVSIZE < sizeof(*val) || v < LLONG_MAX) {
[  258s]       |                                    ^
[  258s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2168:56: error: comparison is always true due to limited range of data type [-Werror=type-limits]
[  258s]  2168 |     if (IVSIZE <= sizeof(*val) || (v >= LLONG_MIN && v <= LLONG_MAX)) {
[  258s]       |                                                        ^
```

**Comment by j-mracek** [comment] 2023-09-20 10:42
@Conan-Kudo May I ask you for a confirmation whether the issue is still valid with the upstream? Recently we fixed several issue related to 32 bits builds.

**Comment by Conan-Kudo** [comment] 2023-09-20 14:49
I don't know as since 5.1.3 (and now 5.1.4), I have this problem: #904

**Comment by Conan-Kudo** [comment] 2023-09-21 10:22
This issue still exists (though because I remove `-Werror` in my builds, it's only a warning):

```
[  168s] [ 36%] Building CXX object bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o
[  168s] cd /home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build/bindings/perl5/libdnf5 && /usr/bin/c++ -DPROJECT_BINARY_DIR=\"/home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build\" -DPROJECT_SOURCE_DIR=\"/home/abuild/rpmbuild/BUILD/dnf5-5.1.4\" -DPROJECT_VERSION_MAJOR=5 -DPROJECT_VERSION_MINOR=1 -DPROJECT_VERSION_PATCH=4 -Dperl5_common_EXPORTS -I/home/abuild/rpmbuild/BUILD/dnf5-5.1.4/include -I/home/abuild/rpmbuild/BUILD/dnf5-5.1.4/common -I/usr/lib/perl5/5.38.0/i586-linux-thread-multi/CORE -fomit-frame-pointer -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -O2 -g -DNDEBUG -std=gnu++20 -fPIC -fmacro-prefix-map=/home/abuild/rpmbuild/BUILD/dnf5-5.1.4/= -Wall -Wextra -Wcast-align -Wformat-nonliteral -Wmissing-format-attribute -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wwrite-strings -Werror=unused-result -Wodr -Wconversion -Wl,--as-needed -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=3 -Wno-cast-align -Wno-conversion -Wno-deprecated-copy -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-missing-declarations -Wno-missing-field-initializers -Wno-sign-compare -Wno-sometimes-uninitialized -Wno-strict-aliasing -Wno-unused-function -Wno-unused-parameter -Wno-catch-value -Wno-maybe-uninitialized -Wno-volatile -MD -MT bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o -MF CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o.d -o CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o -c /home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx
[  168s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx: In function 'int SWIG_AsVal_long_SS_long(SV*, long long int*)':
[  168s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2161:36: warning: comparison is always true due to limited range of data type [-Wtype-limits]
[  168s]  2161 |     if (UVSIZE < sizeof(*val) || v < LLONG_MAX) {
[  168s]       |                                    ^
[  168s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2168:56: warning: comparison is always true due to limited range of data type [-Wtype-limits]
[  168s]  2168 |     if (IVSIZE <= sizeof(*val) || (v >= LLONG_MIN && v <= LLONG_MAX)) {
[  168s]       |                                                        ^
[  168s] At top level:
[  168s] cc1plus: note: unrecognized command-line option '-Wno-sometimes-uninitialized' may have been intended to silence earlier diagnostics
[  168s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/dnf5-5.1.4/build'
```

If I put `-Werror` back, it's an error again.

**Comment by ppisar** [comment] 2023-09-21 10:37
The bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx file is generated by SWIG tool. With Fedora's swig-4.1.1-9.fc39.x86_64 and perl-devel-5.38.0-500.fc39.x86_64 with 64-bit integers and DNF5 at commit e54c233ac8b8de537ee3c9f278aa0be7b2fc2ded, the file does not contain the offending code:

~~~~
$ grep LLONG_MAX  bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx 
#if !defined(SWIG_NO_LLONG_MAX)
# if !defined(LLONG_MAX) && defined(__GNUC__) && defined (__LONG_LONG_MAX__)
#   define LLONG_MAX __LONG_LONG_MAX__
#   define LLONG_MIN (-LLONG_MAX - 1LL)
#   define ULLONG_MAX (LLONG_MAX * 2ULL + 1ULL)
#if defined(LLONG_MAX) && !defined(SWIG_LONG_LONG_AVAILABLE)
     * (UVSIZE <= sizeof(*val) || v <= ULLONG_MAX) */
    if (v >= 0 && (IVSIZE <= sizeof(*val) || v <= ULLONG_MAX)) {
~~~~~

The most similar is the last line and that uses ULLONG_MAX.
Here <https://kojipkgs.fedoraproject.org//packages/dnf5/5.1.4/1.fc40/data/logs/i686/build.log> is build log from i686 machine for DNF5 14 commits ago and it passes.

Can you reproduce it with current Perl, SWIG, and DNF5? Does your perl uses 64-bit integers (perl -V | grep USE_64_BIT_INT)?

The error says that a type of "v" variable (IV probably) is narrower than long long int. That could be true with Perl built without 64-bit integers. I.e. Perl configured without -Duse64bitint. Nonetheless, DNF5 does not use any customization for Perl binding. Hence whole responsibility goes for SWIG <https://github.com/swig/swig/issues>.

**Comment by Conan-Kudo** [comment] 2023-09-21 10:45
> The error says that a type of "v" variable (IV probably) is narrower than long long int. That could be true with Perl built without 64-bit integers. I.e. Perl configured without -Duse64bitint. Nonetheless, DNF5 does not use any customization for Perl binding. Hence whole responsibility goes for SWIG https://github.com/swig/swig/issues.

Yes, it looks like we don't do that for 32-bit non PPC arches: https://code.opensuse.org/package/perl/blob/b7b7718055fcc0de312e4abf83a3aa1730993e57/f/perl.spec#_205-207

**Comment by ppisar** [comment] 2023-09-22 07:13
Please bear in mind that enabling 64-bit integers in perl changes perl ABI. If OpenSUSE maintainers accept the enablement, they will apply it when rebasing perl to a next version.

If you want a real fix, you have to go to Swig.

However, in this case an error on reaching a tautological condition because of type-limits is simple an error in configuration. The condition in SWIG code is correct because needs to deal with varying perl IV type. In one way it's a GCC error, that it reports a warning on optimized out code.

I'm going to close this issue as the root cause is not in DNF5, neither a work around can be applied to DNF5 code.

**Closed by ppisar** 2023-09-22 07:13 UTC

**Comment by ppisar** [comment] 2023-09-25 11:43
What DNF5 can do is remove -Wtype-limits from CMakeLists.txt. (Technically replace it with -Wno-type-limits after -Wextra.)

I don't find -Wtype-limits much helpful: If a compiler can warn about it, it can detect the case. And if it can detect the case, it can optimize out the condition and the binary will be as performant as if the condition was removed.
