### ISSUE TITLE
dnf5 changelog plugin shows improper info for --upgrades

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#481] opened 2023-04-21 11:38 UTC
When a package's upgrade is added into repos, ''dnf5 changelog --upgrades" shows all changelog entries instead of the new ones only.  At the same time, dnf4 shows the correct info. The package has been installed via dnf5.
~~~
# rpm -q tstpkgchlog
tstpkgchlog-1.0-1.noarch
# dnf5 changelog --upgrades tstpkgchlog
Updating and loading repositories:
Repositories loaded.
Listing only new changelogs since installed version of the package
Changelogs for tstpkgchlog-1.0-2.noarch, tstpkgchlog-1.0-2.src
* Wed Jun 20 12:00:00 2018 Tim Developer 1.0-2
- change for testing changelog plugin

* Tue Jun 19 12:00:00 2018 Joe Tester 1.0-1
- initial version

# dnf changelog --upgrades tstpkgchlog
Last metadata expiration check: 0:09:51 ago on Fri 21 Apr 2023 07:23:12 AM EDT.
Listing only new changelogs since installed version of the package
Changelogs for tstpkgchlog-1.0-2.noarch, tstpkgchlog-1.0-2.src
* Wed Jun 20 12:00:00 AM 2018 Tim Developer 1.0-2
- change for testing changelog plugin

#
~~~

**Comment by evan-goode** [comment] 2023-04-24 13:21
Hi, I believe this issue should be fixed as of a12f7c07638c3fd000b16cd6c40e26bf0bccc5dd now that #353 is merged. The issue was that changelog data was not being loaded for the system repository, so the latest changelogs were not being found correctly.

Could you see if the problem is still there?

**Comment by glum23** [comment] 2023-05-03 12:28
@evan-goode, it seems to work OK now, thanks

**Comment by j-mracek** [comment] 2023-05-03 12:56
If I am not mistaken the issue is fixed therefore I am closing the issue.

**Closed by j-mracek** 2023-05-03 12:56 UTC
