### ISSUE TITLE
Repo download progress output goes to stdout instead of stderr (and breaks `repoquery --quiet`)

### ISSUE THREAD

**Issue by jlebon** [rpm-software-management/dnf5#1915] opened 2024-11-29 14:34 UTC
E.g.

```
$ dnf5 repoquery  --repofrompath=tmp,"file://$PWD/overrides/rpm"             --disablerepo '*' --enablerepo tmp --refresh --latest-limit 1             --exclude '*.src' --quiet > out.txt
$ head -n 3 out.txt
 tmp                                    100% |   0.0   B/s |   1.5 KiB |  00m00s
bpftool-0:7.3.0-427.47.1.el9_4.x86_64
kernel-0:5.14.0-427.47.1.el9_4.x86_64
```

**Comment by kontura** [comment] 2024-12-02 08:32
This is a duplicate of https://github.com/rpm-software-management/dnf5/issues/1361.
Plus it is already fixed you may have some older version.

**Closed by kontura** 2024-12-02 08:32 UTC
