### ISSUE TITLE
dnf5 offline-upgrade fails with toml error(s)

### ISSUE THREAD

**Issue by sebastiaanfranken** [rpm-software-management/dnf5#1704] opened 2024-09-17 21:33 UTC
On Fedora 42/Rawhide running `dnf offline-upgrade download -y` works as it should and downloads any updates. The next step `dnf offline-upgrade reboot` fails with a DNF5/toml error:

```
Error reading state: [error] toml::parse_file: invalid table key
 --> /usr/lib/sysimage/libdnf5/offline/offline-transaction-state.toml
   |
 1 | [
   |  ^-- expected basic key([a-zA-Z0-9_-]) or quoted key(" or ')
. Rerun the command you used to initiate the offline transaction, e.g. `dnf5 system-upgrade download [OPTIONS]`.
```

Which appears related to #1186 . The toml file mentioned (`/usr/lib/sysimages/libdnf5/offline/offline-transaction-state.toml`) has the following:

```
[
    "offline-transaction-state",
    {module_platform_id = "", poweroff_after = false, verb = "upgrade", system_releasever = "rawhide", target_releasever = "rawhide", cachedir = "/var/cache/libdnf5", status = "download-complete", cmd_line = "dnf offline-upgrade download -y", state_version = 1},
]
```

Info about my system (`dnf --version`):
```sh
dnf5 version 5.2.6.0
dnf5 plugin API version 2.0
libdnf5 version 5.2.6.0
libdnf5 plugin API version 2.0

Loaded dnf5 plugins:
  name: builddep
  version: 1.0.0
  API version: 2.0

  name: changelog
  version: 1.0.0
  API version: 2.0

  name: config-manager
  version: 0.1.0
  API version: 2.0

  name: copr
  version: 0.1.0
  API version: 2.0

  name: needs_restarting
  version: 1.0.0
  API version: 2.0

  name: repoclosure
  version: 1.0.0
  API version: 2.0
```

**Comment by ppisar** [comment] 2024-09-18 08:22
Duplicate of #1693.

**Closed by ppisar** 2024-09-18 08:22 UTC

**Comment by sebastiaanfranken** [comment] 2024-09-26 23:48
Something odd was going on in that case, since the latest update (yesterday, for this machine) pulled in a update to dnf5 (libdnf5) version 5.2.6.2 which indeed fixed this. Thanks for the assist.
