### ISSUE TITLE
proxy settings in dnf.conf are not applied

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#465] opened 2023-04-18 12:57 UTC
[RHEL issue. It works in RHEL for dnf4.] When proxy* settings like proxy, proxy_username, proxy_password, etc. are present in dnf.conf, dnf5 does not apply them. Note: when the settings are in .repo config files, they work as expected for dnf5.

**Comment by j-mracek** [comment] 2023-11-07 14:24
@glum23 My I ask you, is there any test that covers the problem (CI upstream or downstream)

**Comment by j-mracek** [comment] 2023-11-08 07:33
I tried incorrect value combination in dnf.conf (`proxy_username`) and it looks like that it is correctly propagated. See comparison with DNF4. Definitely the report is not user friendly in comparison to DNF4.

```
$ sudo dnf install acpi --refresh
Error: repo 'copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly': 'proxy_username' is set but not 'proxy_password'
Error: repo 'copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable': 'proxy_username' is set but not 'proxy_password'
Error: repo 'beaker-client': 'proxy_username' is set but not 'proxy_password'
Error: repo 'fedora': 'proxy_username' is set but not 'proxy_password'

$ sudo dnf5 install acpi --refresh
Updating and loading repositories:
Error checking if metalink "https://mirrors.fedoraproject.org/metalink?repo=fedora-38&arch=x86_64" is in sync for repository "fedora"
 Option value is not set
```

**Comment by j-mracek** [comment] 2023-11-08 09:42
I tested it with `dnf5-5.1.4-1` and it looks like that values are correctly propagated from `/etc/dnf/dnf.conf` to repo configuration.

**Comment by glum23** [comment] 2023-11-08 10:17
has been tested with downstream test (involving proxy_username, proxy_password, proxy_auth_method), on fedora-39, dnf5-5.1.6-20231108004735.16.ga2bd24c7.fc40, passed

**Comment by j-mracek** [comment] 2023-11-08 10:42
Closing because the issue is not reproducible anymore. Thank you @glum23 for the report and retesting.

**Closed by j-mracek** 2023-11-08 10:42 UTC
Labels: Priority: HIGH, Triaged
