### ISSUE TITLE
dnf5 must provide a man page for dnf.conf file

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#742] opened 2023-07-20 07:50 UTC
The man page should also cover new `#!include` directive introduced by https://github.com/rpm-software-management/dnf5/pull/741

**Comment by jan-kolarik** [comment] 2023-09-08 07:03
I guess this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/309 ?

**Comment by jan-kolarik** [comment] 2024-01-02 13:41
Closing as duplicate and also the #741 was eventually closed.

**Closed by jan-kolarik** 2024-01-02 13:41 UTC
