### ISSUE TITLE
Does not recognise packages added to existing groups by other repos

### ISSUE THREAD

**Issue by chandradeepdey** [rpm-software-management/dnf5#1847] opened 2024-11-10 18:11 UTC
After adding RPM Fusion
```
# dnf update @core
```
has no effect.

```
# dnf4 group info core
Group: Core
 Description: Smallest possible installation
 Mandatory Packages:
   audit
   basesystem
   bash
   coreutils
   curl
   dhcp-client
   dnf5
   e2fsprogs
   filesystem
   glibc
   hostname
   iproute
   iputils
   kbd
   less
   man-db
   ncurses
   openssh-clients
   openssh-server
   parted
   policycoreutils
   procps-ng
   rootfiles
   rpm
   rpmfusion-free-release
   rpmfusion-nonfree-release
   selinux-policy-targeted
   setup
   shadow-utils
   sssd-common
   sssd-kcm
   sudo
   systemd
   util-linux
   vim-minimal
 Default Packages:
   NetworkManager
   dnf5-plugins
   dracut-config-rescue
   firewalld
   fwupd
   plymouth
   systemd-resolved
   zram-generator-defaults
 Optional Packages:
   dracut-config-generic
   initial-setup
   initscripts
 Conditional Packages:
   rpmfusion-free-appstream-data
   rpmfusion-nonfree-appstream-data
```

```
# dnf group info core
Id                   : core
Name                 : Core
Description          : Smallest possible installation
Installed            : yes
Order                : 
Langonly             : 
Uservisible          : no
Repositories         : @System
Mandatory packages   : audit
                     : basesystem
                     : bash
                     : coreutils
                     : curl
                     : dhcp-client
                     : dnf5
                     : e2fsprogs
                     : filesystem
                     : glibc
                     : hostname
                     : iproute
                     : iputils
                     : kbd
                     : less
                     : man-db
                     : ncurses
                     : openssh-clients
                     : openssh-server
                     : parted
                     : policycoreutils
                     : procps-ng
                     : rootfiles
                     : rpm
                     : selinux-policy-targeted
                     : setup
                     : shadow-utils
                     : sssd-common
                     : sssd-kcm
                     : sudo
                     : systemd
                     : util-linux
                     : vim-minimal
Default packages     : NetworkManager
                     : dnf5-plugins
                     : dracut-config-rescue
                     : firewalld
                     : fwupd
                     : plymouth
                     : systemd-resolved
                     : zram-generator-defaults
Optional packages    : dracut-config-generic
                     : initial-setup
                     : initscripts
```

The RPM Fusion packages are only listed in the dnf4 command.
Version         : dnf5-5.2.6.2-1.fc41

**Comment by kontura** [comment] 2024-11-11 07:01
I believe this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/183.

**Closed by kontura** 2024-11-11 07:01 UTC
