### ISSUE TITLE
Unversioned `Obsoletes(..)` in `.spec` file causes `dnf builddep` to segfault

### ISSUE THREAD

**Issue by coffeejunk** [rpm-software-management/dnf5#1873] opened 2024-11-19 20:04 UTC
An unversioned `Obsoletes(..)` in a `.spec` file causes `dnf builddep` to segfault:

**unversioned:**
```
# cat /root/rpmbuild/SPECS/sample.spec
Name:           hello_world
Version:        0.1.0
Release:        1%{?dist}
Summary:        sample

License:        MIT
URL:            https://github.com/rpm-software-management/dnf5

BuildArch:      noarch

Source0:        %{name}-%{version}.tar.gz

Obsoletes:      vim

%description
This is a demo


# dnf -y builddep /root/rpmbuild/SPECS/sample.spec
Updating and loading repositories:
Repositories loaded.
Segmentation fault (core dumped)
```

**versioned:**
```
# cat /root/rpmbuild/SPECS/sample.spec
Name:           hello_world
Version:        0.1.0
Release:        1%{?dist}
Summary:        sample

License:        MIT
URL:            https://github.com/rpm-software-management/dnf5

BuildArch:      noarch

Source0:        %{name}-%{version}.tar.gz

Obsoletes:      vim < 1

%description
This is a demo


# dnf -y builddep /root/rpmbuild/SPECS/sample.spec
Updating and loading repositories:
Repositories loaded.
Nothing to do.
```

**Comment by kontura** [comment] 2024-11-20 12:21
Thanks for the report, I believe this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/1864.

It should be already fixed by: https://github.com/rpm-software-management/dnf5/pull/1870.

I have just tested it with a local build that includes the most recent changes it is working.

**Closed by kontura** 2024-11-20 12:21 UTC
