### ISSUE TITLE
[dnf4->dnf5] builddep no longer accepts `--spec`

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/dnf5#1841] opened 2024-11-05 20:09 UTC
In rpm-ostree's CI we do this: `dnf builddep --spec -y packaging/rpm-ostree.spec --allowerasing`

It looks like there's [~400 other instances on Github](https://github.com/search?q=%22dnf+builddep+--spec%22+-is%3Afork&type=code).

Basically we want this stuff to work with at least c9s too, so we'd have to grow "detect dnf4 vs dnf5" and it seems a lot easier to just readd `--spec` to dnf5.

**Comment by kontura** [comment] 2024-11-06 11:10
I think this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/799.

**Closed by kontura** 2024-11-06 11:10 UTC
Labels: DNF4 compatibility
