### ISSUE TITLE
The "Complete!" message of dnf upgrade overlaps with the old log

### ISSUE THREAD

**Issue by junjieyuan** [rpm-software-management/dnf5#1899] opened 2024-11-25 17:25 UTC
Please see the second to last line:

![vlcsnap-2024-11-26-01h01m45s986](https://github.com/user-attachments/assets/71c2e24e-7119-49db-9784-a66fe4842a0d)

"dnf upgrade" video:

https://github.com/user-attachments/assets/15f2bf10-c752-4086-bd86-5f39e1cbc5a5

OS: Fedora Server 41
<details>
<summary>dnf --version</summary>

dnf5 version 5.2.7.0
dnf5 plugin API version 2.0
libdnf5 version 5.2.7.0
libdnf5 plugin API version 2.0

Loaded dnf5 plugins:
  name: automatic
  version: 1.0.0
  API version: 2.0

  name: builddep
  version: 1.0.0
  API version: 2.0

  name: changelog
  version: 1.0.0
  API version: 2.0

  name: config-manager
  version: 0.1.0
  API version: 2.0

  name: copr
  version: 0.1.0
  API version: 2.0

  name: needs_restarting
  version: 1.0.0
  API version: 2.0

  name: repoclosure
  version: 1.0.0
  API version: 2.0
</details>

**Comment by rnayabed** [comment] 2024-11-26 08:26
Bump: https://discussion.fedoraproject.org/t/dnf5-misses-a-newline-before-printing-the-final-transaction-result/138365

**Comment by kontura** [comment] 2024-11-26 08:34
Thanks for the report, I am setting a high priority because a lot of people sees this.
I am think it is likely caused by https://github.com/rpm-software-management/dnf5/pull/1805.

**Comment by avinal** [comment] 2024-11-27 09:01
I saw the `Complete!ng` and thought this was a spelling mistake. There is also an incomplete `arch` or `noarch` probably due to the same issue.
```
Complete!ng trigger-install scriptlet: glibc-common-0:2.40-12.fc41.x86_6464c41.x86_64hrch
```

**Comment by geraldosimiao** [comment] 2024-12-04 04:03
It seem's the fix didn't get to the new f42 build https://bodhi.fedoraproject.org/updates/FEDORA-2024-de59b25ef6
![Screenshot_20241204_005436](https://github.com/user-attachments/assets/73f9570c-bb6b-44dc-bad1-90baa4061fa6)

**Comment by ppisar** [comment] 2024-12-04 11:31
Of course not because there is no fix yet.

**Comment by kontura** [comment] 2024-12-05 11:23
This should be fixed by: https://github.com/rpm-software-management/dnf5/pull/1925

**Closed by kontura** 2024-12-05 11:23 UTC
Labels: Priority: HIGH, Triaged
