### ISSUE TITLE
Localization not working for dnf5

### ISSUE THREAD

**Issue by NorwayFun** [rpm-software-management/dnf5#1395] opened 2024-04-10 07:02 UTC
Hello,

I'm unsuccessfully trying to get localized messages from dnf5:

![image](https://github.com/rpm-software-management/dnf5/assets/72336380/deef7949-dd5c-4671-bf1b-f43a4ddeb117)

Works with dnf4, but doesn't with dnf5. Yes, translations are there, it's 100% translated on weblate.

Temuri

**Comment by pkratoch** [comment] 2024-04-10 07:16
Yes, the issue is valid, however, it's a duplicate of https://github.com/rpm-software-management/dnf5/issues/1375 , so I am closing it.

**Closed by pkratoch** 2024-04-10 07:16 UTC
