### ISSUE TITLE
`test_transaction` tests fail on 64-bit RISC-V (riscv64)

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#740] opened 2023-07-20 01:31 UTC
When building on openSUSE Tumbleweed for RISC-V, the test suite fails with the following data:

```
[ 5126s] test_transaction.cpp:113:Assertion
[ 5126s] Test name: RpmTransactionTest::test_transaction
[ 5126s] equality assertion failed
[ 5126s] - Expected: 0
[ 5126s] - Actual  : 5
[ 5126s] 
[ 5126s] test_transaction.cpp:143:Assertion
[ 5126s] Test name: RpmTransactionTest::test_transaction_temp_files_cleanup
[ 5126s] assertion failed
[ 5126s] - Expression: !std::filesystem::exists(package_path)
```

Here's the full build log from openSUSE: [dnf5-5.1.0-openSUSE-TW-RISCV64-buildlog.txt](https://github.com/rpm-software-management/dnf5/files/12101237/dnf5-5.1.0-openSUSE-TW-RISCV64-buildlog.txt)

It is also failing in Fedora for RISC-V in the same way, and a sample log is present here: [dnf5-5.0.14-Fedora-38-RISCV64-buildlog.txt](https://github.com/rpm-software-management/dnf5/files/12101236/dnf5-5.0.14-Fedora-38-RISCV64-buildlog.txt)

**Comment by Conan-Kudo** [comment] 2023-07-20 01:34
Koji build task logs: http://fedora.riscv.rocks/koji/taskinfo?taskID=1456036

cc: @rwmjones @davidlt

**Comment by Conan-Kudo** [comment] 2023-09-25 14:10
This is still a problem with DNF 5.1.4.

**Comment by jan-kolarik** [comment] 2023-09-27 06:26
This is a duplicate of https://github.com/rpm-software-management/dnf5/issues/503. I will close this one to put everything to the single place.

**Closed** 2023-09-27 06:26 UTC
