### ISSUE TITLE
Terrible DNF with nohup

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/dnf5#818] opened 2023-08-14 18:30 UTC
Running DNF from graphical session, I typically use `nohup` to save the update session from the DE crashes. Later, I observe the progress via `tail -f noup.out`. However, the output looks terrible, something such as:

~~~
$ tail -f nohup.out 
 tecla                                                    x86_64 45~beta-1.fc40                  rawhide                   113.6 KiB

Transaction Summary:
 Installing:        7 packages
 Upgrading:       328 packages
 Replacing:       331 packages

Total size of inbound packages is 818 MiB. Need to download 818 MiB.
After this operation 55 MiB will be freed (install 3 GiB, remove 3 GiB).
[  1/335] geocode-glib-0:3.26.4-8.fc40. 100% | 495.9 KiB/s |  71.4 KiB |  00m00s[  2/335] tecla-0:45~beta-1.fc40.x86_64 100% | 249.5 KiB/s |  41.4 KiB |  00m00s[  3/335] libeis-0:1.0.0-2.fc39.x86_64  100% |   1.4 MiB/s |  51.4 KiB |  00m00s[  4/335] libimobiledevice-glue-0:1.0.0 100% |   1.1 MiB/s |  36.1 KiB |  00m00s[  5/335] libertas-firmware-0:20230804- 100% |   5.2 MiB/s | 542.1 KiB |  00m00s[  6/335] python3-backoff-0:2.2.1-4.fc3 100% | 478.0 KiB/s |  42.1 KiB |  00m00s[  7/335] mozjs115-0:115.1.0-1.fc40.x86 100% |   8.6 MiB/s |   4.6 MiB |  00m01s[  8/335] NetworkManager-libnm-1:1.44.0 100% |   4.2 MiB/s |   1.8 MiB |  00m00s[  9/335] NetworkManager-1:1.44.0-1.fc4 100% |   4.6 MiB/s |   2.2 MiB |  00m00s[ 10/335] NetworkManager-wwan-1:1.44.0- 100% | 278.7 KiB/s |  59.1 KiB |  00m00s[ 11/335] NetworkManager-wifi-1:1.44.0- 100% |   1.9 MiB/s | 132.8 KiB |  00m00s[ 12/335] NetworkManager-ppp-1:1.44.0-1 100% | 783.6 KiB/s |  36.0 KiB |  00m00s[ 13/335] NetworkManager-bluetooth-1:1. 100% |   1.0 MiB/s |  53.5 KiB |  00m00s[ 14/335] NetworkManager-adsl-1:1.44.0- 100% | 442.1 KiB/s |  27.4 KiB |  00m00s[ 15/335] NetworkManager-config-connect 100% | 186.1 KiB/s |  13.0 KiB |  00m00s[ 16/335] adobe-mappings-cmap-0:2023062 100% |   8.2 MiB/s |   2.1 MiB |  00m00s[ 17/335] adobe-mappings-cmap-deprecate 100% | 533.7 KiB/s | 113.1 KiB |  00m00s[ 18/335] alsa-sof-firmware-0:2.2.6-1.f 100% |   7.5 MiB/s |   3.4 MiB |  00m00s[ 19/335] alternatives-0:1.25-1.fc39.x8 100% | 147.6 KiB/s |  38.5 KiB |  00m00s[ 20/335] at-spi2-atk-0:2.49.90-1.fc39. 100% | 151.8 KiB/s |  85.7 KiB |  00m01s[ 21/335] at-spi2-core-0:2.49.90-1.fc39 100% | 648.9 KiB/s | 371.2 KiB |  00m01s[ 22/335] amd-gpu-firmware-0:20230804-1 100% |  12.9 MiB/s |  19.0 MiB |  00m01s[ 23/335] atk-0:2.49.90-1.fc39.x86_64   100% | 124.6 KiB/s |  81.2 KiB |  00m01s[ 24/335] audit-libs-0:3.1.2-1.fc39.x86 100% | 303.3 KiB/s | 117.1 KiB |  00m00s[ 25/335] audit-0:3.1.2-1.fc39.x86_64   100% | 684.4 KiB/s | 269.0 KiB |  00m00s[ 26/335] python3-audit-0:3.1.2-1.fc39. 100% | 234.5 KiB/s |  87.0 KiB |  00m00s[ 27/335] autocorr-cs-1:7.5.5.2-2.fc39. 100% | 210.8 KiB/s |  78.4 KiB |  00m00s[ 28/335] atheros-firmware-0:20230804-1 100% |  14.2 MiB/s |  21.7 MiB |  00m02s[ 29/335] autocorr-en-1:7.5.5.2-2.fc39. 100% | 896.1 KiB/s | 110.2 KiB |  00m00s[ 30/335] brcmfmac-firmware-0:20230804- 100% |  15.4 MiB/s |   9.6 MiB |  00m01s[ 31/335] ca-certificates-0:2023.2.60_v 100% |   1.6 MiB/s | 837.2 KiB |  00m01s[ 32/335] chkconfig-0:1.25-1.fc39.x86_6 100% | 339.0 KiB/s | 173.6 KiB |  00m01s[ 33/335] chrony-0:4.4-1.fc40.x86_64    100% |   6.2 MiB/s | 332.1 KiB |  00m00s[ 34/335] codec2-0:1.2.0-2.fc39.x86_64  100% |   8.0 MiB/s | 637.7 KiB |  00m00s[ 35/335] lpcnetfreedv-0:0.5-2.fc40.x86 100% |  10.1 MiB/s |   7.3 MiB |  00m01s[ 36/335] libavcodec-free-0:6.0-11.fc39 100% |   5.6 MiB/s |   4.1 MiB |  00m01s[ 37/335] libavformat-free-0:6.0-11.fc3 100% |   1.5 MiB/s |   1.1 MiB |  00m01s[ 38/335] libavfilter-free-0:6.0-11.fc3 100% |   5.8 MiB/s |   1.5 MiB |  00m00s[ 39/335] libavdevice-free-0:6.0-11.fc3 100% | 328.4 KiB/s |  90.0 KiB |  00m00s[ 40/335] libavutil-free-0:6.0-11.fc39. 100% |   1.3 MiB/s | 338.8 KiB |  00m00s[ 41/335] libswresample-free-0:6.0-11.f 100% |   1.1 MiB/s |  68.9 KiB |  00m00s[ 42/335] libpostproc-free-0:6.0-11.fc3 100% |   1.1 MiB/s |  49.3 KiB |  00m00s[ 43/335] libswscale-free-0:6.0-11.fc39 100% |   2.7 MiB/s | 190.5 KiB |  00m00s[ 44/335] cups-1:2.4.6-4.fc40.x86_64    100% |   6.7 MiB/s |   1.5 MiB |  00m00s[ 45/335] cups-client-1:2.4.6-4.fc40.x8 100% | 392.2 KiB/s |  72.6 KiB |  00m00s[ 46/335] cups-filesystem-1:2.4.6-4.fc4 100% |  77.7 KiB/s |  12.4 KiB |  00m00s[ 47/335] cups-filters-1:2.0~rc2-3.fc39 100% |   5.9 MiB/s | 215.9 KiB |  00m00s[ 48/335] cups-libs-1:2.4.6-4.fc40.x86_ 100% |   4.8 MiB/s | 267.8 KiB |  00m00s[ 49/335] curl-0:8.2.1-2.fc40.x86_64    100% |   3.2 MiB/s | 345.7 KiB |  00m00s[ 50/335] cups-ipptool-1:2.4.6-4.fc40.x 100% |  12.0 MiB/s |   3.9 MiB |  00m00s[ 51/335] libcurl-minimal-0:8.2.1-2.fc4 100% | 931.1 KiB/s | 257.9 KiB |  00m00s[ 52/335] openssl-libs-1:3.1.1-1.fc39.x 100% |   8.9 MiB/s |   2.2 MiB |  00m00s[ 53/335] openssl-1:3.1.1-1.fc39.x86_64 100% |  10.3 MiB/s |   1.0 MiB |  00m00s[ 54/335] dash-0:0.5.12-1.fc39.x86_64   100%

... snip ...
~~~

Please note that the code block above is in reality wrapped to the terminal width. But in any case, I don't think this is optimal. I assume, that the output would be similar if it was just piped to the file.

~~~
$ rpm -q dnf5
dnf5-5.1.1-1.fc39.x86_64
~~~

**Comment by jan-kolarik** [comment] 2023-08-15 05:20
This is probably related to https://github.com/rpm-software-management/dnf5/issues/692.

**Comment by j-mracek** [comment] 2023-08-23 15:11
I am closing the issue as duplicate of #692

**Closed by j-mracek** 2023-08-23 15:11 UTC
