### ISSUE TITLE
dnf 5 translate.

### ISSUE THREAD

**Issue by x-gyba** [rpm-software-management/dnf5#1955] opened 2024-12-14 14:40 UTC
![Captura de tela de 2024-12-14 11-10-31](https://github.com/user-attachments/assets/1eab4b53-a9e4-4a62-87d0-50eada15b780)
Sorry, it was already posted here, but this also happens in PT-BR.

**Comment by kontura** [comment] 2024-12-16 08:01
Yes, this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/1868.

**Closed by kontura** 2024-12-16 08:01 UTC
